data:
  mainPage:
    url: https://bim360field.autodesk.com
    title: BIM 360 Field Web

  login:
    emailwrong:
      username: 
      password: 
    passwordwrng:
      username: 
      password: 
    correct:
      username: 
      password: 
